[workspace]
members = [
    "bin/bot",
    "bin/cli",
    "crates/artemis-core",
    "crates/generator",
    "crates/strategies/*",
    "crates/db",
    "crates/bindings",
    "crates/shared", 
    "integration", "crates/types",
]

default-members = ["bin/bot", "bin/cli", "crates/shared", "crates/db","crates/artemis-core", "crates/bindings"]
resolver = "2"

[workspace.dependencies]
## eth


[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'
