[workspace]
members = [
    "bin/artemis",
    "bin/cli",
    # "bin/playground",
    "crates/artemis-core",
    "crates/generator",
    "crates/strategies/*",
    "crates/bindings",
    "crates/shared", 
    "integration",
]

default-members = ["bin/artemis", "bin/cli", "crates/shared", "crates/artemis-core", "crates/bindings"]
resolver = "2"

[workspace.dependencies]
## eth


[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'

[net]
git-fetch-with-cli = true