[package]
name = "bot"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"


[dependencies]
tokio = { workspace = true }
eyre = { workspace = true }
dotenv = "0.15.0"
async-trait = "0.1.64"
engine = { path = "../../crates/engine" }
futures = "0.3.27"
generalized-arb-strategy = { path = "../../crates/strategies/generalized-arb" }
bindings = { path = "../../crates/bindings" }
shared = { path = "../../crates/shared" }
anyhow = "1.0.70"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
clap = { version = "4.2.5", features = ["derive"] }
alloy-chains = { workspace = true }
alloy = { workspace = true }
log = "0.4.22"
env_logger = "0.11.4"
