[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { workspace = true }
tokio = { workspace = true }
alloy-chains = { workspace = true }
eyre = { workspace = true }
alloy-primitives = { workspace = true }

shared = { path = "../../crates/shared" }
uni-tri-arb-strategy = { path = "../../crates/strategies/uni-tri-arb" }
types = { path = "../../crates/types" }
artemis-core = { path = "../../crates/artemis-core" }
addressbook = { path = "../../crates/addressbook" }
provider = { path = "../../crates/provider" }

anyhow = "1.0.70"
clap = { version = "4.2.5", features = ["derive"] }
dotenv = "0.15.0"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
