[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1.0.70"
generator = { path = "../../crates/generator" }
clap = { version = "4.2.5", features = ["derive"] }
tokio = { version = "1.18", features = ["full"] }
uni-tri-arb-strategy = { path = "../../crates/strategies/uni-tri-arb" }
shared = { path = "../../crates/shared" }
alloy-chains = "0.1.0"
alloy = "0.2.1"
dotenv = "0.15.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
types = { path = "../../crates/types" }


