[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0.0", features = ["postgres"] }
diesel_migrations = "2.0.0"
serde = { version = "1" }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }