[package]
name = "uni-tri-arb-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { git = "http://github.com/alloy-rs/alloy", features = ["sol-types", "contract"] }

[net]
git-fetch-with-cli = true